### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'listConnectionsCopy'

### ISSUE THREAD

**Issue by ManuWasabi** [SleatherT/CodyFight-Bot#11]
Anyone can help me with this error?

Process Process-1:
Traceback (most recent call last):
  File "C:\Users\manuw\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\manuw\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\manuw\Downloads\CodyFight-Bot-main\CodyFight-Bot-main\hunterbot.py", line 130, in bot
    loopGames(player, stopFlag)
  File "C:\Users\manuw\Downloads\CodyFight-Bot-main\CodyFight-Bot-main\hunterbot.py", line 95, in loopGames
    player.displayInfo()
  File "C:\Users\manuw\Downloads\CodyFight-Bot-main\CodyFight-Bot-main\core\client.py", line 285, in displayInfo
    finalStr = getMap(self.jsonResponse)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manuw\Downloads\CodyFight-Bot-main\CodyFight-Bot-main\core\nodemap.py", line 1416, in getMap
    graphObject = Graph(jsonResponse)
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\manuw\Downloads\CodyFight-Bot-main\CodyFight-Bot-main\core\nodemap.py", line 835, in __init__
    for connection in self.ryoNode.listConnectionsCopy:
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'listConnectionsCopy'

**Comment by SleatherT** [comment]
Sorry for the delay, are you still encountering this error?
